first task fix

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -6,21 +6,13 @@ if [ $# -1t 4 ]
 then
 	echo "Usage: O-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
 	exit 1
-fi
-
-#paramentals to variables
-
-path_to_file=$1
-ip=$2
-username=$3
-path_to_shh_key=$4
-
-# strict host key checking
-scp -o "strictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "Susername@$ip:~/"
-# checking
-if [ $? -eq 0 ]
-then
-echo "FILE WAS TRANSFERED SUCCESSFULLY"
 else
-echo "FILE TRANSFER FAILED"
+	# strict host checking
+	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
+
+	if [ $? -eq 0 ]
+	then
+		echo "FILE WAS TRANSFERED SUCCESSFULLY"
+	else
+		echo "FILE TRANSFER FAILED"
 fi
